name: Build, Test, and Prepare Release Candidate

on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize

jobs:
  integration-tests:
    name: Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'Extension Release Candidate :rocket:' )
    strategy:
      matrix:
        java: [8, 11, 16]
    services:
      cassandra-3:
        image: liquibase/liquibase:cassandra-test-3
        ports:
        - "9042:9042"
      cassandra-4:
        image: liquibase/liquibase:cassandra-test-4
        ports:
          - "9043:9042"
    steps:
    - uses: actions/checkout@v2
    - name: Cache Local Maven Repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: 'adopt'
    - name: Test With Maven
      run: mvn surefire:test --file pom.xml
